version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: digest_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: digest_redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tg_bot:
    build: .
    container_name: tg_bot
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - PROXY_HOST=global_xray_client
    volumes:
      - .:/app
    networks:
      - default
      - proxy-network

  digest_pipeline:
    build: .
    container_name: digest_pipeline
    restart: always
    command: sh -c "alembic upgrade head && python main.py"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - PROXY_HOST=global_xray_client
    volumes:
      - .:/app
    networks:
      - default
      - proxy-network

volumes:
  postgres_data:
  redis_data:

networks:
  proxy-network:
    external: true
    name: proxy-network
