"""Константы приложения."""

DEFAULT_CHEAP_MODEL = "google/gemini-2.5-flash"
DEFAULT_EXPENSIVE_MODEL = "deepseek/deepseek-v4-pro"

DEFAULT_CACHE_TTL_DAYS = 30
DEFAULT_CUTOFF_HOURS = 24
DEFAULT_WEEKLY_QUIZ_DAYS = 7

DEFAULT_MAX_QUESTIONS_PER_QUIZ = 5
MAX_TELEGRAM_MESSAGE_LENGTH = 3500
