"""add_poll_mapping

Revision ID: 30ab56836579
Revises: fcd9e3c660fb
Create Date: 2026-05-28 12:22:13.376790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ab56836579'
down_revision: Union[str, Sequence[str], None] = 'fcd9e3c660fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.String(length=256), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('correct_option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_mappings_poll_id'), 'poll_mappings', ['poll_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_mappings_poll_id'), table_name='poll_mappings')
    op.drop_table('poll_mappings')
    # ### end Alembic commands ###
