"""add_original_user_answer_id_to_poll_mapping

Revision ID: 6076ae5a68b0
Revises: 8dcca26b3202
Create Date: 2026-05-28 14:37:20.616051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6076ae5a68b0'
down_revision: Union[str, Sequence[str], None] = '8dcca26b3202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_mappings', sa.Column('original_user_answer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'poll_mappings', 'user_answers', ['original_user_answer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll_mappings', type_='foreignkey')
    op.drop_column('poll_mappings', 'original_user_answer_id')
    # ### end Alembic commands ###
