"""add_is_published_to_digest

Revision ID: 709842ea8c9d
Revises: 30ab56836579
Create Date: 2026-05-28 14:23:57.081016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709842ea8c9d'
down_revision: Union[str, Sequence[str], None] = '30ab56836579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'is_published')
    # ### end Alembic commands ###
