"""add_question_index_to_poll_mapping

Revision ID: 8dcca26b3202
Revises: 709842ea8c9d
Create Date: 2026-05-28 14:36:38.517435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcca26b3202'
down_revision: Union[str, Sequence[str], None] = '709842ea8c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_mappings', sa.Column('question_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_mappings', 'question_index')
    # ### end Alembic commands ###
