"""add_post_media_path

Revision ID: d59f4df00ba2
Revises: 7a3ea1cb26bb
Create Date: 2026-06-04 11:32:29.517652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59f4df00ba2'
down_revision: Union[str, Sequence[str], None] = '7a3ea1cb26bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media_path')
    # ### end Alembic commands ###
