"""add ondelete behavior

Revision ID: e75781dc335f
Revises: 01f9f25fd81d
Create Date: 2026-05-12 14:28:15.245705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75781dc335f'
down_revision: Union[str, Sequence[str], None] = '01f9f25fd81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_digest_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'digests', ['digest_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('quizzes_digest_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'digests', ['digest_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_digest_id_fkey'), 'quizzes', 'digests', ['digest_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_digest_id_fkey'), 'posts', 'digests', ['digest_id'], ['id'])
    # ### end Alembic commands ###
