"""add_is_comments_poll

Revision ID: fcc1d8034480
Revises: d59f4df00ba2
Create Date: 2026-06-10 13:48:38.708894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc1d8034480'
down_revision: Union[str, Sequence[str], None] = 'd59f4df00ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_mappings', sa.Column('is_comments_poll', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_mappings', 'is_comments_poll')
    # ### end Alembic commands ###
