TG_SOURCES = [
    'tips_ai',
    'ai_machinelearning_big_data', # также есть дайджесты    
    'neuro_channel',
    'pro_ai_news',  
    'ai_newz',
    'data_secrets',
    'seeallochnaya',
    'lovedeathtransformers',
    'addmeto',
    'maxvotek',
    'kantor_ai',
    'mountainai_info',
    'cryptovalerii',
    'AIexTime',
    'senior_augur',
    'ml4value',
    'cryptoEssay',
    'AGI_and_RL',
    'rybolos_channel',
    'oulenspiegel_channel',
    'reliable_ml',
    'not_boring_ds',
    'adel_and_ml',
    'gonzo_ML',
    'sinecor',
    'datafest',
    'vikulin_ai',
    'oestick',
    'the_ai_architect',
    'new_yorko_times',
    'jdata_blog',
    'nadlskom',
    'dealerAI',
    'llm_under_hood',
    'doomgrad',
    'aaanalytics',
    'dzis_science',
    'data_science_winners',
    'abstractDL',
    'blognot',
    'stuffyNLP',
    'MLunderhood',
    'zheltyi_ai'
    
]
# дата крайнего ревью - 17.07

TG_SOURCES = list(set(TG_SOURCES))
